[feat] Nullable fields
icebob/fastest-validator pull request #191
Opened 2020-09-28 14:50 UTC by erfanium

Related #113

2020-09-30 19:08 UTC, icebob requested changes

2020-09-30 19:08 UTC, icebob commented on test/integration.spec.js
> +describe("Test optional option", () => {
Why these both tests are duplicated?

2020-09-30 19:08 UTC, icebob commented on test/integration.spec.js
> +});
Please add test when 
- `nullable: true` and there is `default`
- `optional: true` and there is `default`
- `nullable: true` and `optional: true`
- `nullable: true` and `optional: true` and there is `default`

2020-10-01 11:03 UTC, erfanium commented on lib/validator.js
> +			let defaultValue = JSON.stringify(rule.schema.default);
Thank!

2020-10-01 11:06 UTC, erfanium commented on test/integration.spec.js
> +describe("Test optional option", () => {
I have no answer😁😁

2020-10-07 08:57 UTC, icebob approved these changes
Thanks!

2020-10-07 08:57 UTC, merged

2020-10-20 12:48 UTC, icebob commented
@erfanium could you ping me on Discord chat, please? https://discord.gg/TSEcDRP