Update README.md
icebob/fastest-validator pull request #255
Opened 2021-07-08 14:57 UTC by erfanium

A redo for #227

2021-07-09 19:11 UTC, icebob requested changes
Wow, great job.

2021-07-09 19:11 UTC, icebob commented on README.md
> +check({ cc: "452373989901198" }); // Valid
Missing `v.compile`

2021-07-10 07:05 UTC, erfanium commented on README.md
> +check({ cc: "452373989901198" }); // Valid
Looks like there's something wrong with my regex replace script😁

2021-07-11 11:20 UTC, icebob approved these changes

2021-07-11 11:24 UTC, merged