fix(multi): item rule has custom checker will throw error if validate…
icebob/fastest-validator pull request #290
Opened 2022-03-15 09:59 UTC by 0x0a0d

… failed

custom checker push errors to fnCustomErrorsX that will be assigned to var errors, not _errors as expected
To avoid a breaking changes, I just keep size of errors before validate and restore it if failed
But I think the logic should be changed
![image](https://user-images.githubusercontent.com/32500015/158353324-eb324481-6988-4ae8-9123-3a9830c4a6f7.png)

2022-03-15 23:17 UTC, 0x0a0d commented
I add some test that will break with current master branch

2022-03-16 18:40 UTC, icebob requested changes

2022-03-16 18:40 UTC, icebob commented on test/rules/multi.spec.js
> +				expect(check(o)).not.toBe(true);
Same

2022-03-18 05:36 UTC, 0x0a0d commented
@erfanium pls fix this too

2022-03-21 20:20 UTC, icebob approved these changes
Thanks!

2022-03-21 20:20 UTC, merged